services:
  web:
    build:
      context: ./backend  # 👈 ONLY backend is built
    working_dir: /code    # 👈 Set working dir to /code
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
      - "DATABASE_URL=postgresql://postgres:postgres@db:5432/art_moving"
    volumes:
      - ./backend:/code   # 👈 Mount only the backend
    networks:
      - art_moving_network


  db:
    image: postgres:15
    container_name: art_moving_react_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: art_moving
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    networks:
      - art_moving_network

volumes:
  postgres_data:

networks:
  art_moving_network:
