services:
  web:
    build:
      context: ./backend
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/art_moving
    volumes:
      - ./backend:/code
    networks:
      - art_moving_network

  db:
    image: postgres:15
    container_name: art_moving_react_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: art_moving
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    networks:
      - art_moving_network

volumes:
  postgres_data:

networks:
  art_moving_network:
